apiVersion: v1
kind: ReplicationController
metadata:
  name: configmap-loadbalancer-rc
  labels:
    app: configmap-loadbalancer
spec:
  replicas: 1
  selector:
    app: configmap-loadbalancer
  template:
    metadata:
      labels:
        app: configmap-loadbalancer
    spec:
      containers:
      - image: kokhang/configmap-loadbalancer:0.1
        imagePullPolicy: Always
        name: configmap-loadbalancer
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 3306
          hostPort: 3306
      #   securityContext:
      #     privileged: true
      # hostNetwork: true


