apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap-coffee-svc
    labels:
        loadbalancer: configmap
data:
    host: "foo.bar.com"
    namespace: "default"
    bind-port: "80"
    target-service-name: "coffee-svc"
    target-port: "80"
    ssl: "false"
    path: "/coffee"
