apiVersion: v1
kind: ConfigMap
metadata:
    name: configmap-mysql-svc
    labels:
        loadbalancer: configmap
data:
    host: "mysql.bar.com"
    namespace: "default"
    bind-port: "3306"
    target-service-name: "mysql-service"
    target-port: "3306"
    ssl: "false"
